//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSearchingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Benefit
    {
        public Benefit()
        {
            this.DesiredBenefits = new HashSet<DesiredBenefit>();
            this.JobBenefits = new HashSet<JobBenefit>();
        }
    
        public int BenefitID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<DesiredBenefit> DesiredBenefits { get; set; }
        public virtual ICollection<JobBenefit> JobBenefits { get; set; }
    }
}
