//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSearchingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyInfo
    {
        public CompanyInfo()
        {
            this.CompanyInfoCities = new HashSet<CompanyInfoCity>();
        }
    
        public string RecruiterID { get; set; }
        public string LogoURL { get; set; }
        public string Company { get; set; }
        public string Address { get; set; }
        public string District { get; set; }
        public string PhoneNumber { get; set; }
        public string Description { get; set; }
        public bool IsVisible { get; set; }
    
        public virtual Recruiter Recruiter { get; set; }
        public virtual ICollection<CompanyInfoCity> CompanyInfoCities { get; set; }
    }
}
