//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSearchingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public string UserID { get; set; }
        public string FullName { get; set; }
        public bool Gender { get; set; }
        public bool MaritalStatus { get; set; }
        public bool Nationality { get; set; }
        public string Address { get; set; }
        public System.DateTime DateofBirth { get; set; }
        public string PhoneNumber { get; set; }
        public string AvatarUrl { get; set; }
        public int CityID { get; set; }
        public string District { get; set; }
        public bool IsVisible { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual City City { get; set; }
    }
}
