//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSearchingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationHistory
    {
        public int EducationHistoryID { get; set; }
        public string Subject { get; set; }
        public string School { get; set; }
        public int SchoolLevel_ID { get; set; }
        public string Achievement { get; set; }
        public int ProfileID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual SchoolLevel SchoolLevel { get; set; }
    }
}
