//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSearchingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public Job()
        {
            this.AppliedJobs = new HashSet<AppliedJob>();
            this.JobBenefits = new HashSet<JobBenefit>();
            this.JobCategories = new HashSet<JobCategory>();
            this.JobCities = new HashSet<JobCity>();
            this.JobLanguages = new HashSet<JobLanguage>();
            this.JobSkills = new HashSet<JobSkill>();
        }
    
        public int JobID { get; set; }
        public string RecruiterID { get; set; }
        public string JobTitle { get; set; }
        public Nullable<decimal> MinSalary { get; set; }
        public Nullable<decimal> MaxSalary { get; set; }
        public string JobDescription { get; set; }
        public string JobRequirement { get; set; }
        public int JobLevel_ID { get; set; }
        public int MinSchoolLevel_ID { get; set; }
        public long JobView { get; set; }
        public Nullable<System.DateTime> StartedDate { get; set; }
        public Nullable<System.DateTime> EndedDate { get; set; }
        public Nullable<int> PurchaseJobPackageId { get; set; }
        public bool IsPublic { get; set; }
    
        public virtual ICollection<AppliedJob> AppliedJobs { get; set; }
        public virtual JobLevel JobLevel { get; set; }
        public virtual PurchaseJobPackage PurchaseJobPackage { get; set; }
        public virtual Recruiter Recruiter { get; set; }
        public virtual SchoolLevel SchoolLevel { get; set; }
        public virtual ICollection<JobBenefit> JobBenefits { get; set; }
        public virtual ICollection<JobCategory> JobCategories { get; set; }
        public virtual ICollection<JobCity> JobCities { get; set; }
        public virtual ICollection<JobLanguage> JobLanguages { get; set; }
        public virtual ICollection<JobSkill> JobSkills { get; set; }
    }
}
