//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSearchingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobLanguage
    {
        public int LanguageID { get; set; }
        public int JobID { get; set; }
        public string Description { get; set; }
        public int MinLevel_ID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual Language Language { get; set; }
        public virtual Level Level { get; set; }
    }
}
