//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSearchingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobPackage
    {
        public JobPackage()
        {
            this.PurchaseJobPackages = new HashSet<PurchaseJobPackage>();
        }
    
        public int JobPackageID { get; set; }
        public string Name { get; set; }
        public int JobNumber { get; set; }
        public int PostDuration { get; set; }
        public bool IsHighlight { get; set; }
        public bool IsCategoryPriority { get; set; }
        public bool IsHomepagePosting { get; set; }
        public Nullable<int> ViewMultiNumber { get; set; }
        public string MoreDescription { get; set; }
        public decimal Cost { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<PurchaseJobPackage> PurchaseJobPackages { get; set; }
    }
}
