//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSearchingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jobseeker
    {
        public Jobseeker()
        {
            this.AppliedJobs = new HashSet<AppliedJob>();
            this.DesiredBenefits = new HashSet<DesiredBenefit>();
            this.OwnSkills = new HashSet<OwnSkill>();
            this.Profiles = new HashSet<Profile>();
        }
    
        public string JobSeekerID { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<AppliedJob> AppliedJobs { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<DesiredBenefit> DesiredBenefits { get; set; }
        public virtual ICollection<OwnSkill> OwnSkills { get; set; }
        public virtual ICollection<Profile> Profiles { get; set; }
    }
}
