//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSearchingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class OwnSkill
    {
        public int Skill_ID { get; set; }
        public string JobSeekerID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Jobseeker Jobseeker { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
