//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSearchingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public Profile()
        {
            this.AppliedJobs = new HashSet<AppliedJob>();
            this.EducationHistories = new HashSet<EducationHistory>();
            this.EmploymentHistories = new HashSet<EmploymentHistory>();
            this.ExpectedCategories = new HashSet<ExpectedCategory>();
            this.ExpectedCities = new HashSet<ExpectedCity>();
            this.ReferencePersons = new HashSet<ReferencePerson>();
            this.ViewProfiles = new HashSet<ViewProfile>();
        }
    
        public int ProfileID { get; set; }
        public string Name { get; set; }
        public int YearOfExperience { get; set; }
        public int HighestSchoolLevel_ID { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public Nullable<int> Level_ID { get; set; }
        public string MostRecentCompany { get; set; }
        public string MostRecentPosition { get; set; }
        public Nullable<int> CurrentJobLevel_ID { get; set; }
        public string ExpectedPosition { get; set; }
        public int ExpectedJobLevel_ID { get; set; }
        public decimal ExpectedSalary { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public System.DateTime UpdatedTime { get; set; }
        public string Objectives { get; set; }
        public int PercentStatus { get; set; }
        public string JobSeekerID { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<AppliedJob> AppliedJobs { get; set; }
        public virtual ICollection<EducationHistory> EducationHistories { get; set; }
        public virtual ICollection<EmploymentHistory> EmploymentHistories { get; set; }
        public virtual ICollection<ExpectedCategory> ExpectedCategories { get; set; }
        public virtual ICollection<ExpectedCity> ExpectedCities { get; set; }
        public virtual JobLevel JobLevel { get; set; }
        public virtual JobLevel JobLevel1 { get; set; }
        public virtual Jobseeker Jobseeker { get; set; }
        public virtual Language Language { get; set; }
        public virtual Level Level { get; set; }
        public virtual SchoolLevel SchoolLevel { get; set; }
        public virtual ICollection<ReferencePerson> ReferencePersons { get; set; }
        public virtual ICollection<ViewProfile> ViewProfiles { get; set; }
    }
}
