//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSearchingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseAdvertise
    {
        public int PurchaseAdsID { get; set; }
        public int AdvertiseID { get; set; }
        public string RecuiterID { get; set; }
        public string LogoUrl { get; set; }
        public string LinkUrl { get; set; }
        public System.DateTime PurchasedDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool IsVisible { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string ManagerID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Advertise Advertise { get; set; }
        public virtual Manager Manager { get; set; }
        public virtual Recruiter Recruiter { get; set; }
    }
}
