//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSearchingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolLevel
    {
        public SchoolLevel()
        {
            this.EducationHistories = new HashSet<EducationHistory>();
            this.Jobs = new HashSet<Job>();
            this.Profiles = new HashSet<Profile>();
        }
    
        public int SchoolLevel_ID { get; set; }
        public string Name { get; set; }
        public int LevelNum { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<EducationHistory> EducationHistories { get; set; }
        public virtual ICollection<Job> Jobs { get; set; }
        public virtual ICollection<Profile> Profiles { get; set; }
    }
}
