//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSearchingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewProfile
    {
        public string RecruiterID { get; set; }
        public int ProfileID { get; set; }
        public System.DateTime ViewedDate { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual Recruiter Recruiter { get; set; }
    }
}
